openapi: 3.0.0
info:
  title: Terrrrr Backend API
  version: 1.0.0
paths:
  /api/auth/session:
    get:
      tags:
        - Auth Session
      summary: Verifies the user's JWT session
      description: Checks the httpOnly JWT cookie named `token` and verifies if the user is authenticated. The backend reads the token using `request.cookies.token`. You must be signed in and have a valid JWT cookie to access this endpoint.
      responses:
        "200":
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true
        "400":
          description: Missing or invalid token
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "No token"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid token"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: false
                  error:
                    type: string
