openapi: 3.0.0
info:
  title: Terrrrr Backend API
  version: 1.0.0
paths:
  /api/user/fetchUserById:
    get:
      tags:
        - User Profile
      summary: Get authenticated user's profile
      description: Returns the authenticated user's ID and username. Requires authentication via JWT cookie.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
        "401":
          description: Unauthorized (if not authenticated)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
