openapi: 3.0.0
info:
  title: Terrrrr API
  version: 1.0.0
paths:
  /api/user/signup:
    post:
      tags:
        - User Signing Up
      summary: Endpoint for user registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
