openapi: 3.0.0
info:
  title: Terrrrr API
  version: 1.0.0
paths:
  /api/user/signout:
    post:
      tags:
        - User Sign Out
      summary: Endpoint for user sign out
      description: Clears authentication cookies and removes the refresh token from the database.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "401":
          description: Unauthorized (if not authenticated)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
