openapi: 3.0.0
info:
  title: Terrrrr Backend API
  version: 1.0.0
paths:
  /api/world/join/{id}:
    post:
      tags:
        - Worlds
      summary: Join a world
      description: Allows an authenticated user to join a world by its ID. The world ID is provided as a path parameter. Requires authentication via JWT cookie.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the world to join.
      responses:
        "200":
          description: Joined world successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        "401":
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
